### ISSUE TITLE
initialzation error please check config

### ISSUE THREAD

**Issue by SpoderKerman** [PapaJoesSoup/BDMk22Plugin#1]
so i keep getting this error from bdmk22 and it started when i installed the mod.

**Comment by PapaJoesSoup** [comment]
I think I know what It might be... move the configuration file to the bdmk22 folder and see if it works.

**Comment by SpoderKerman** [comment]
excuse me ... um what config files, the one in bdmk22 folder or the RPM one?

**Comment by DoctorDavinci** [comment]
What other mods, if any, are you using?

**Comment by SpoderKerman** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20867151/17501560/fa2564ce-5dad-11e6-85cd-4c26a381da7f.png)

**Comment by SpoderKerman** [comment]
I fixed a problem that involves the HUD switch not showing up but the monitors and sounds don't work from the High G ground Prox etc...

**Comment by SpoderKerman** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20867151/17502316/df740c50-5db4-11e6-8703-fb3b7eaf04b0.png)

**Comment by Nerfclasher** [comment]
Did you install ASETS props mod because it is a  dependency

**Comment by SpoderKerman** [comment]
NerfClasher I have but its outdated from 2015 maybe that's the problem tho I can't seem to find a link for aset props

**Comment by Nerfclasher** [comment]
here is a link for the latest version
http://forum.kerbalspaceprogram.com/index.php?/topic/116430-ivaprops-aset-props-pack-v13-for-the-modders-who-create-iva%C3%A3%C2%A2%C3%A2%E2%80%9A%C2%AC%C3%A2%E2%80%9E%C2%A2s/&page=3#comment-2432890

**Comment by gomker** [comment]
@SpoderKerman  
New release should address any outstanding issues.
We have noted the location of the latest ASET and RPM to use.
